version: "3"
services: 
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    ports: 
      - 5000:5000
    networks:
      - b208
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    container_name: backend
    build: 
      context: ./backend/a105
    ports: 
      - 8080:8080
    networks:
      - b208
    restart: unless-stopped
networks: 
  b208:
